-keep class com.usageinsights.models.** { *; }
-keep class com.usageinsights.receivers.** { *; }
-keep class com.usageinsights.services.** { *; }
-keep class com.usageinsights.workers.** { *; }
-dontwarn okhttp3.**
